### ISSUE TITLE
Specifying min/max speeds for players

### ISSUE THREAD

**Issue by madan96** [simon-lc/AlgamesPlots.jl#6]
Hi, I know the `Player` object allows us to specify the speeds for the initial and final state of the player. But is there any way to specify the minimum, maximum and perhaps even target speeds for the entire trajectory of the player? Thanks!

**Comment by simon-lc** [comment]
You're right with `Player` you can specify a goal state `xf` which contains a goal velocity. Increasing the cost `Q` on this dimension of the state will encourage the system to track this desired velocity more closely. 
In addition to this, I added the `StateBoundConstraint` to Algames in v0.1.4. You can check out how to use this new constraint in the example file: https://github.com/simon-lc/Algames.jl/blob/master/examples/intro_example.jl
It should be easy to add min/max constraints on the velocity with this constraint type especially if you're using the unicycle or bicycle model. 
Which dynamics model are you using to run your experiements?

**Comment by madan96** [comment]
Thanks for adding this! I'll take a look.
I'm using the unicycle model for my experiments.

**Comment by madan96** [comment]
I had a look at the `add_state_bound` function. I'm slightly confused about how to exactly use this for all the agents. I saw the example you shared, where even though you specify it for just one player, you are passing a `SVector` that has a length of `size([x,,y,theta,v]) * number_of_players`. Shouldn't it be setting the bounds for `[x,y,theta,v]` of a single agent?

**Comment by simon-lc** [comment]
That's a really good remark! I think that the solution that you get might be different if you impose the state constraint (e.g. v of player 1 < 0.5) on all agents compared to only applying it on player 1. So to keep it as general as possible I left the player's index `i` as an argument.
I think that in your case the way to go would be to identify the velocity indices of all players: `iv = [4, 8]`. Then create the state constraint with `x_min = -Inf*ones(n); x_min[iv]=[v1_min, v2_min] ` add same for `x_max`. And add this constraint to all vehicles `i = 1 and 2`.

**Comment by simon-lc** [comment]
Since you're using unicycle, the velocity constraint will fit perfectly with the state constraint template. The double integrator would have been trickier.

**Comment by madan96** [comment]
Thanks! I tried adding the bound and the constraints seem to exceed the epsilon values for all the episodes. I think this might have something to do with the fact that the solver is always beginning with max throttle action (sharing the throttle profile for the 2 agent case below. y-axis is the throttle action value). Is there anything I might be doing wrong here? I tried increasing the `Q` cost but that didn't really help.
![Figure_2](https://user-images.githubusercontent.com/13871064/115459940-44769f80-a245-11eb-8121-b98be6e89576.png)

**Comment by simon-lc** [comment]
I don't know exactly what's the scenario you're trying to solve. If you have a MWE that I can run, I can look into this!

**Comment by madan96** [comment]
My bad! I'm solving for the four-way intersection. Here's a MWE (I also save a csv file that you can use to plot the states and controls wrt time): https://pastebin.com/0mp8UjeP

Besides this, I also added the code snippet below in `src/scenario/scenario.jl` of `AlgamesDriving`.
```
x_min = -Inf*ones(n)
x_max = Inf*ones(n)
for i = 1:p
    player = sce.player[i]
    x_min[4*i] = 0.0
    x_max[4*i] = player.xf[4]
end

for i = 1:p
    add_state_bound!(game_con, i, x_max, x_min)
end
```
I also noticed this behavior where after the cars pass the intersection, they move at really low speeds irrespective of the target speed. Not sure if it happens intentionally as part of the solution that the solver comes up with.

**Comment by madan96** [comment]
HI @simon-lc, did you get a chance to look at this^?

**Comment by simon-lc** [comment]
@madan96 Yes I am working on this this morning. I have a demo running, I still need to add tests and push.

**Comment by simon-lc** [comment]
I added a velocity-limit example based on your MWE, I updated Algames.jl to v0.1.5 and AlgamesDriving to v.0.1.3.
This is a plot of the velocity, I added a (v_max~0.85) constraint on the fastest player
![Screenshot from 2021-04-28 12-56-01](https://user-images.githubusercontent.com/39047348/116464712-27cc0000-a821-11eb-9f83-83d7a45c1444.png)

Tell me if you have issues with it!

**Comment by simon-lc** [comment]
Oh I forgot,
_I also noticed this behavior where after the cars pass the intersection, they move at really low speeds irrespective of the target speed. Not sure if it happens intentionally as part of the solution that the solver comes up with._
I think this is because, in the MWE you sent, the cost function had a cost on the position of the vehicle along the lane it is following. Therefore it is optimal for the vehicle to slow down after the intersection to get to the goal position as quickly as possible and then stay there. 
I lowered this cost to 1e-2 in the speed limit example therefore the cost term that dominates is the speed term. Therefore the vehicle will try to maintain a constant speed during the whole trajectory.

**Comment by madan96** [comment]
Thanks! This works pretty well now. I noticed that upon reducing the cost for the position, the car steers in a rather un-smooth way. I guess playing around with the cost function should fix this. But seems to be working well other than that :)

**Comment by simon-lc** [comment]
That's awesome! Yes I guess that tuning the cost function should help with this issue.
I am closing the issue, feel free to reopen if there is still an issue with min/max velocity.
