### ISSUE TITLE
LoadError: UndefVarError: plot! not defined

### ISSUE THREAD

**Issue by jchengai** [simon-lc/AlgamesPlots.jl#9]
Hi, thanks for your contribution. 

When I tried to run the `intro_example.jl` with `julia intro_example.jl`, I got the error `LoadError: UndefVarError: plot! not defined`

I tried to add `using Plots` but got another error:
```
ERROR: LoadError: Cannot convert UnicycleGame{12, 6, 3, Vector{SVector{2, Int64}}, Vector{SVector{2, Int64}}, Vector{SVector{4, Int64}}} to series data for plotting
```

I'm not quite familiar with Julia and I wonder if this problem is related to the version of Julia (I use 1.6.1). Or is there any instruction to run the minimum example?

**Comment by simon-lc** [comment]
Hi, 
Thanks for pointing this out! I added instructions on how to run the intro example in the readme. 
You need to install Plots to run the `plot()` command, you need to install `Algames#v0.1.6` which defines plotting recipes to run `plot(prob.stats)`. 
I am using Julia 1.6.0 but I think it should be fine with 1.6.1.
Tell me if you still have an issue
